import type { Metadata } from "next";
import "./globals.css";
import { WalletProviderComponent } from "./context/walletcontext";

export const metadata: Metadata = {
  title: "Blinks Splash",
  description: "Generated by create next app",
};

export default function RootLayout({ children}: Readonly<{children: React.ReactNode}>){
  return (
    <html lang="en">
      <body>
        <WalletProviderComponent>
          {children}
        </WalletProviderComponent>
      </body>
    </html>
  )
}